version: '3'
services:
  app:
    build: .
    container_name: collection-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - app_collection_network
  db:
    image: postgres:alpine
    restart: always
    container_name: collection-db
    environment:
      - POSTGRES_DB=collection-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app_collection_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=cntiguita@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_collection_network
networks:
  app_collection_network:

volumes:
  postgres-db:
